echo '--------------------------------------------------'
echo 'I (a) =netstat -a |todas as conexões             I'
echo 'I (b) =netstat -at|todas as conexoes tcp         I'
echo 'I (c) =netstat -au|todas as conexoes udp         I'
echo 'I (d) =netstat -aw|todas as conexoes raw         I'
echo 'I (e) =netstat -aut|todas as conexoes tcp e udp  I'
echo 'I Pressione CRTL+C para sair                     I'
echo '--------------------------------------------------'